package ru.itis.constants;

public enum MessageTypes {
    GAME_START,
    WAITING_FOR_PLAYERS,
    PLAYER_ACCEPTED,
    PLAYER_DISCONNECT,
    WAITING_FOR_ANSWERS,
    TIME_IS_UP,
    WAITING_FOR_OTHER_PLAYERS,
    WAITING_FOR_NEXT_Q,
    GAME_OVER
}
