package ru.itis.constants;

public enum MessageTypes {
    GAME_START,
    GAME_OVER,
    WAITING_FOR_PLAYERS,
    WAITING_FOR_OTHER_PLAYERS,
    WAITING_FOR_ANSWERS,
    WAITING_FOR_NEXT_Q,
    PLAYER_ACCEPTED,
    PLAYER_LEAVE_ROOM,
    PLAYER_JOIN_ROOM,
    PLAYER_JOIN_ROOM_STATUS,
    PLAYER_DISCONNECT,
    ROOM_CREATE,
    TIME_IS_UP,
    SYSTEM_MESSAGE
}
