package ru.itis.constants;

public enum MessageTypes {
    GAME_START,
    GAME_OVER,

    PLAYER_ACCEPTED,
    PLAYER_INIT_USERNAME,
    PLAYER_DISCONNECT,
    PLAYER_LEAVE_ROOM,
    PLAYER_JOIN_ROOM,

    ROOM_CREATE,
    ROOM_CREATE_STATUS,
    UPDATE_ROOM,

    TIME_IS_UP,
    SYSTEM_MESSAGE,

    NEXT_QUESTION,
    RIGHT_ANSWER
}
